apps/trains/urls.py
from django.urls import path
from .views import TrainListView, TrainDetailView, TrainCreateView, TrainUpdateView, TrainDeleteView

app_name = 'trains'
urlpatterns = [
    path('detail/<int:pk>', TrainDetailView.as_view(), name='detail'),
    path('update/<int:pk>', TrainUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', TrainDeleteView.as_view(), name='delete'),
    path('add/', TrainCreateView.as_view(), name='add'),
    path('', TrainListView.as_view(), name='home')
]

travelling/urls.py
from django.contrib import admin
from django.urls import path, include
from travelling.views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('cities/', include('apps.cities.urls', 'cities')),
    path('trains/', include('apps.trains.urls', 'trains')),
    path('', include('apps.routes.urls', 'routes')),
]

apps/trains/models.py
from django.db import models
from apps.cities.models import City
from django.core.exceptions import ValidationError


class Train(models.Model):
    name = models.CharField('Название', max_length=80, unique=True)
    from_city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='Откуда', related_name='from_city')
    to_city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='Куда', related_name='to_city')
    travel_time = models.IntegerField('Время в пути')

    class Meta:
        verbose_name = 'Поезд'
        verbose_name_plural = 'Поезда'
        # ordering = ['travel_time']

    def __str__(self):
        return f'Поезд № {self.name} из {self.from_city} в {self.to_city}'

    def clean(self, *args, **kwargs):
        if self.from_city == self.to_city:
            raise ValidationError('Измените город прибытия на другой')
        qs = Train.objects.filter(from_city=self.from_city,
                                  to_city=self.to_city, travel_time=self.travel_time).exclude(pk=self.pk)
        if qs:
            raise ValidationError('Измените время в пути')
        return super(Train, self).clean()

apps/trains/forms.py
from django import forms
from .models import Train
from ..cities.models import City


class TrainForm(forms.ModelForm):
    name = forms.CharField(label='Название',
                           widget=forms.TextInput(
                               attrs={
                                   'class': 'form-control',
                                   'placeholder': ' Введите название поезда'
                               }))
    from_city = forms.ModelChoiceField(label='Откуда', queryset=City.objects.all(),
                                       widget=forms.Select(
                                           attrs={
                                               'class': 'form-control'
                                           }
                                       ))
    to_city = forms.ModelChoiceField(label='Куда', queryset=City.objects.all(),
                                     widget=forms.Select(
                                         attrs={
                                             'class': 'form-control'
                                         }
                                     ))
    travel_time = forms.CharField(label='Время в пути',
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'placeholder': ' Введите время в пути'
                                      }))

    class Meta:
        model = Train
        fields = ('name', 'from_city', 'to_city', 'travel_time')

apps/trains/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import TrainForm
from .models import Train
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


class TrainListView(ListView):
    model = Train
    paginate_by = 5
    template_name = 'trains/home.html'
    context_object_name = 'trains'


class TrainDetailView(DetailView):
    queryset = Train.objects.all()
    template_name = 'trains/detail.html'
    context_object_name = 'train'


class TrainCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Train
    form_class = TrainForm
    login_url = '/login/'
    template_name = 'trains/create.html'
    success_url = reverse_lazy('trains:home')
    success_message = 'Поезд успешно создан'


class TrainUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Train
    form_class = TrainForm
    login_url = '/login/'
    template_name = 'trains/update.html'
    success_url = reverse_lazy('trains:home')
    success_message = 'Поезд успешно отредактирован'


class TrainDeleteView(LoginRequiredMixin, DeleteView):
    model = Train
    login_url = '/login/'
    template_name = 'trains/delete.html'
    success_url = reverse_lazy('trains:home')

templates/trains/create.html
{% extends 'base.html' %}
{% block title %}Создать поезд{% endblock %}
{% block content %}
    <div class="container my-4">
        <h1 class="display-4">Создать поезд</h1>
        <div class="row mx-auto my-4">
            <div class="col-md-4">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-light" type="submit" role="button" value="Сохранить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/trains/delete.html
{% extends 'base.html' %}
{% block title %}Удалить поезд{% endblock %}
{% block content %}
    <div class="container my-4">
        <h3 class="">Удалить поезд</h3>
        <div class="row mx-auto my-4">
            <div class="col-md-6  my-4">
                <form action="" method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить "{{ object.name }}"?</p>
                    <input class="btn btn-light" type="submit" role="button" value="Удалить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/trains/detail.html
{% extends 'base.html' %}
{% block title %}Поезд {{ object.name }}{% endblock title %}
{% block content %}
    <div class="container my-4">
    <h1 class="text-center my-4">Обзор поезда</h1>
       <div class="row">
            <div class="col-md-10 mx-auto">
                <table class="table">
                    <thead class="thead-dark rounded">
                    <tr>
                        <th scope="col">Название поезда</th>
                        <th scope="col">Откуда</th>
                        <th scope="col">Куда</th>
                        <th scope="col">Время в пути</th>
                        <th scope="col">&nbsp;</th>
                        <th scope="col">&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">{{ train.name }}</th>
                            <th>{{ train.from_city }}</th>
                            <th>{{ train.to_city }}</th>
                            <th>{{ train.travel_time }} ч.</th>
                            <td><a class="btn btn-success btn-sm" href="{% url 'trains:update' pk=train.pk %}"
                                   role="button">Редактировать</a></td>
                            <td><a class="btn btn-danger btn-sm" href="{% url 'trains:delete' pk=train.pk %}"
                                   role="button">Удалить</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
       </div>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <a href="{% url 'trains:home' %}">
                    <button type="button" class="btn btn-light">
                        К списку поездов
                    </button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/trains/home.html
{% extends 'base.html' %}
{% block title %}Список поездов{% endblock title %}
{% block content %}
    <div class="container my-4">
        <h1 class="text-center my-4">Список поездов</h1>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <table class="table">
                    <thead class="thead-dark rounded">
                    <tr>
                        <th scope="col">Название поезда</th>
                        <th scope="col">Откуда</th>
                        <th scope="col">Куда</th>
                        <th scope="col">Время в пути</th>
                        <th scope="col">&nbsp;</th>
                        <th scope="col">&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for train in trains %}
                        <tr>
                            <th scope="row"><a href="{% url 'trains:detail' pk=train.pk %}">{{ train.name }}</a></th>
                            <th>{{ train.from_city }}</th>
                            <th>{{ train.to_city }}</th>
                            <th>{{ train.travel_time }} ч.</th>
                            <td><a class="btn btn-success btn-sm" href="{% url 'trains:update' pk=train.pk %}"
                                   role="button">Редактировать</a></td>
                            <td><a class="btn btn-danger btn-sm" href="{% url 'trains:delete' pk=train.pk %}"
                                   role="button">Удалить</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% if page_obj.paginator.num_pages  != 1 %}
        <div class="row">
            <div class="col-md-10 mx-auto">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                 <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                     <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                             <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                        {% endif %}
                        <li class="page-item disabled"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    {% endif %}
    </div>
{% endblock %}

templates/trains/update.html
{% extends 'base.html' %}
{% block title %}Отредактировать поезд{% endblock %}
{% block content %}
    <div class="container my-4">
        <h1 class="display-4">Отредактировать поезд</h1>
        <div class="row mx-auto my-4">
            <div class="col-md-4">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-light" type="submit" role="button" value="Сохранить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}