apps/cities/urls.py
from django.urls import path
from .views import CityListView, CityCreateView, CityDetailView, CityUpdateView, CityDeleteView

app_name = 'cities'
urlpatterns = [
    path('add/', CityCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', CityDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    path('', CityListView.as_view(), name='home')

]

travelling/urls.py
from django.contrib import admin
from django.urls import path, include
from travelling.views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('cities/', include('apps.cities.urls', 'cities')),
    path('trains/', include('apps.trains.urls', 'trains')),
    path('', include('apps.routes.urls', 'routes')),
]

apps/cities/models.py
from django.db import models


class City(models.Model):
    name = models.CharField('Город', unique=True, max_length=70)

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

    def __str__(self):
        return self.name

apps/cities/forms.py
from django import forms
from .models import City


class CityForm(forms.ModelForm):
    name = forms.CharField(label='Город',
                           widget=forms.TextInput(
                               attrs={
                                   'class': 'form-control',
                                   'placeholder': ' Введите название города'
                               }))

    class Meta:
        model = City
        fields = ('name',)

apps/cities/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from apps.cities.forms import CityForm
from apps.cities.models import City


class CityListView(ListView):
    paginate_by = 5
    model = City
    template_name = 'cities/home.html'
    context_object_name = 'cities'


class CityDetailView(DetailView):
    queryset = City.objects.all()
    template_name = 'cities/detail.html'


class CityCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = City
    form_class = CityForm
    login_url = '/login/'
    template_name = 'cities/create.html'
    success_url = reverse_lazy('cities:home')
    success_message = 'Город успешно создан'


class CityUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = City
    form_class = CityForm
    login_url = '/login/'
    template_name = 'cities/update.html'
    success_url = reverse_lazy('cities:home')
    success_message = 'Город успешно отредактирован'
    
    
class CityDeleteView(LoginRequiredMixin, DeleteView):
    model = City
    login_url = '/login/'
    template_name = 'cities/delete.html'
    success_url = reverse_lazy('cities:home')

templates/cities/create.html
{% extends 'base.html' %}
{% block title %}Создать город{% endblock %}
{% block content %}
    <div class="container my-4">
        <h1 class="display-4">Создать город</h1>
        <div class="row mx-auto my-4">
            <div class="col-md-4">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-light" type="submit" role="button" value="Сохранить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/cities/delete.html
{% extends 'base.html' %}
{% block title %}Удалить город{% endblock %}
{% block content %}
    <div class="container my-4">
        <h3 class="">Удалить город</h3>
        <div class="row mx-auto my-4">
            <div class="col-md-6  my-4">
                <form action="" method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить "{{ object.name }}"?</p>
                    <input class="btn btn-light" type="submit" role="button" value="Удалить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/cities/home.html
{% extends 'base.html' %}
{% block title %}Города{% endblock title %}
{% block content %}
    <div class="container my-4">
        <h1 class="text-center my-4">Список городов</h1>
        <div class="row">
            <div class="col-md-6 mx-auto">
                <table class="table">
                    <thead class="thead-dark rounded">
                    <tr>
                        <th scope="col">Название</th>
                        <th scope="col">&nbsp;</th>
                        <th scope="col">&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for city in cities %}
                        <tr>
                            <th scope="row"><a href="{% url 'cities:detail' pk=city.pk %}">{{ city.name }}</a></th>
                            <td><a class="btn btn-success btn-sm" href="{% url 'cities:update' pk=city.pk %}"
                                   role="button">Редактировать</a></td>
                            <td><a class="btn btn-danger btn-sm" href="{% url 'cities:delete' pk=city.pk %}"
                                   role="button">Удалить</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% if page_obj.paginator.num_pages  != 1 %}
        <div class="row">
            <div class="col-md-6 mx-auto">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                 <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                     <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                             <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                        {% endif %}
                        <li class="page-item disabled"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/cities/update.html
{% extends 'base.html' %}
{% block title %}Редактировать город{% endblock title %}
{% block content %}
    <div class="container my-4">
        <h1 class="display-4">Редактировать город</h1>
        <div class="row mx-auto my-4">
            <div class="col-md-4">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Сохранить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}