apps/cities/urls.py
from django.urls import path
from .views import CityListView, CityCreateView, CityDetailView, CityUpdateView, CityDeleteView

app_name = 'cities'
urlpatterns = [
    path('add/', CityCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', CityDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    path('', CityListView.as_view(), name='home')

]

apps/routes/urls.py
from django.urls import path
from .views import home, find_routes, save_route, RouteListView, RouteDetailView, RouteDeleteView

app_name = 'routes'
urlpatterns = [
    path('find/', find_routes, name='find'),
    path('save_route/<int:route_id>', save_route, name='save_route'),
    path('list/', RouteListView.as_view(), name='list'),
    path('detail/<int:pk>', RouteDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', RouteDeleteView.as_view(), name='delete'),
    path('', home, name='home')
]

apps/trains/urls.py
from django.urls import path
from .views import TrainListView, TrainDetailView, TrainCreateView, TrainUpdateView, TrainDeleteView

app_name = 'trains'
urlpatterns = [
    path('detail/<int:pk>', TrainDetailView.as_view(), name='detail'),
    path('update/<int:pk>', TrainUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', TrainDeleteView.as_view(), name='delete'),
    path('add/', TrainCreateView.as_view(), name='add'),
    path('', TrainListView.as_view(), name='home')
]

travelling/urls.py
from django.contrib import admin
from django.urls import path, include
from travelling.views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('cities/', include('apps.cities.urls', 'cities')),
    path('trains/', include('apps.trains.urls', 'trains')),
    path('', include('apps.routes.urls', 'routes')),
]

templates/base.html
{% url 'cities:home' as cities_home %}
{% url 'trains:home' as trains_home %}
{% url 'routes:list' as routes_list %}
{% url 'login' as login %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
        <a class="navbar-brand" href="{% url 'routes:home' %}">Маршруты by Krivenko E.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item {% if request.path == routes_list %} active {% endif %}">
                    <a class="nav-link" href="{% url 'routes:list' %}">Маршруты</a>
                </li>
                <li class="nav-item {% if request.path == cities_home %} active {% endif %}">
                    <a class="nav-link" href="{% url 'cities:home' %}">Города <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.path == trains_home %} active {% endif %}">
                    <a class="nav-link" href="{% url 'trains:home' %}">Поезда</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Добавление
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'cities:add' %}">Добавить город</a>
                        <a class="dropdown-item" href="{% url 'trains:add' %}">Добавить поезд</a>
                    </div>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Выйти</a></li>
                {% else %}
                    <li class="nav-item {% if request.path == login %} active {% endif %}"><a href="{% url 'login' %}" class="nav-link">Войти</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto my-2">
            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT.MESSAGE.LEVELS.ERROR %}
                        <div class="alert alert-danger messages">
                            <span {% if message.tags %}
                                class="{{ message.tags }}" {% endif %}>Внимание! {{ message }}</span>
                        </div>
                    {% else %}
                        <div class="alert alert-success messages">
                            <span {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</span>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% block content %}
{% endblock content %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('.js-example-basic-single').select2();
        $('.js-example-basic-multiple').select2();
    });
</script>
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="container my-4">
        <h1 class="display-4 text-center">Страница входа</h1>
        <div class="row my-4">
            <div class="col-md-4 mx-auto">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-light" type="submit" role="button" value="Войти">
                </form>
            </div>
        </div>
    </div>
{% endblock %}