apps/routes/urls.py
from django.urls import path
from .views import home, find_routes, save_route, RouteListView, RouteDetailView, RouteDeleteView

app_name = 'routes'
urlpatterns = [
    path('find/', find_routes, name='find'),
    path('save_route/<int:route_id>', save_route, name='save_route'),
    path('list/', RouteListView.as_view(), name='list'),
    path('detail/<int:pk>', RouteDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', RouteDeleteView.as_view(), name='delete'),
    path('', home, name='home')
]

travelling/urls.py
from django.contrib import admin
from django.urls import path, include
from travelling.views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('cities/', include('apps.cities.urls', 'cities')),
    path('trains/', include('apps.trains.urls', 'trains')),
    path('', include('apps.routes.urls', 'routes')),
]

apps/routes/models.py
from django.db import models

from apps.cities.models import City
from apps.trains.models import Train


class Route(models.Model):
    name = models.CharField('Название', max_length=100, unique=True)
    from_city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='Откуда', related_name='route_from_city')
    to_city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='Куда', related_name='route_to_city')
    across_cities = models.ManyToManyField(Train, blank=True, verbose_name='Через города')
    travel_time = models.IntegerField('Время в пути')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Маршурт'
        verbose_name_plural = 'Маршруты'

apps/routes/forms.py
from django import forms
from django.forms.utils import ErrorList

from apps.cities.models import City
from .graph import get_graph, dfs_paths

from .models import Route
from ..trains.models import Train


class RouteForm(forms.Form):
    from_city = forms.ModelChoiceField(label='Откуда', queryset=City.objects.all(),
                                       widget=forms.Select(attrs={'class': 'form-control js-example-basic-single'}))
    to_city = forms.ModelChoiceField(label='Куда', queryset=City.objects.all(),
                                     widget=forms.Select(attrs={'class': 'form-control js-example-basic-single'}))
    across_cities = forms.ModelMultipleChoiceField(label='Через города', queryset=City.objects.all(), required=False,
                                                   widget=forms.SelectMultiple(
                                                       attrs={'class': 'form-control js-example-basic-multiple'}))
    travel_time = forms.CharField(label='Время в пути',
                                  widget=forms.TextInput(
                                      attrs={'class': 'form-control',
                                             'placeholder': ' Введите время в пути'
                                             }))

    def clean(self, *args, **kwargs):
        from_city = self.cleaned_data.get('from_city')
        to_city = self.cleaned_data.get('to_city')
        across_cities_data = self.cleaned_data.get('across_cities')
        travel_time = self.cleaned_data.get('travel_time')
        graph = get_graph()
        all_ways = list(dfs_paths(graph, from_city.id, to_city.id))
        if len(all_ways) == 0:
            raise forms.ValidationError('Маршрута, удовлетворяющего условиям не существует.')
        if across_cities_data:
            across_cities = [city.id for city in across_cities_data]  # получаем id промежуточных точек
            right_ways = []
            for way in all_ways:  # проходимся циклом по всем маршрутам и проверяем промежуточные точки
                if all(point in way for point in across_cities):  # если все точки в маршруте, добавляем в список
                    right_ways.append(way)
            if not right_ways:  # если нет ни одного маршрута с такими точками, возвращаем ошибку
                raise forms.ValidationError('Маршрут через эти города невозможен')
        else:
            right_ways = all_ways

        trains = []
        for route in right_ways:
            tmp = {'trains': []}
            total_time = 0
            for i in range(len(route) - 1):
                qs = Train.objects.filter(from_city=route[i], to_city=route[i + 1])
                qs = qs.order_by('travel_time').first()
                total_time += qs.travel_time
                tmp['trains'].append(qs)
            tmp['total_time'] = total_time
            if total_time <= int(travel_time):
                tmp['from_city'] = from_city
                tmp['to_city'] = to_city
                trains.append(tmp)
        if not trains:
            raise forms.ValidationError('Время в пути больше заданного')
        self.cleaned_data['trains'] = trains
        return super(RouteForm, self).clean()


class DivErrorList(ErrorList):
    def __str__(self):
        return self.as_divs()

    def as_divs(self):
        if not self:
            return ''
        return '<div class="alert alert-secondary" role="alert">' \
               '<h5 class="text-center">Не удалось ничего найти:</h5>%s</div>' % ''.join(['<p class="text-center">%s<p>' % e for e in self])


class RouteCreateForm(forms.ModelForm):
    name = forms.CharField(label='Назовите маршрут', widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))

    class Meta:
        model = Route
        fields = ['name']

apps/routes/admin.py
from django.contrib import admin
from .models import Route

admin.site.register(Route)

apps/routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    name = 'apps.routes'

apps/routes/graph.py
from apps.trains.models import Train


def dfs_paths(graph, start, goal):
    """Функция поиска всех возможных маршрутов
       из одного города в другой. Вариант посещения
       одного и того же города более одного раза,
        не рассматривается.
    """
    stack = [(start, [start])]
    while stack:
        (vertex, path) = stack.pop()
        if vertex in graph.keys():
            for next_ in graph[vertex] - set(path):
                if next_ == goal:
                    yield path + [next_]
                else:
                    stack.append((next_, path + [next_]))


def get_graph():
    qs = Train.objects.values()
    from_city_set = set(i['from_city_id'] for i in qs)
    graph = {}
    for city in from_city_set:
        trains = Train.objects.filter(from_city=city).values('to_city')
        tmp = set(i['to_city'] for i in trains)
        graph[city] = tmp
    return graph

apps/routes/route.py
import copy
from django.conf import settings
from apps.cities.models import City
from apps.trains.models import Train
from django.db.models import Case, When


class SessionRoute:
    def __init__(self, request):
        self.session = request.session
        routes = self.session.get(settings.ROUTE_SESSION_ID)
        if not routes:
            routes = self.session[settings.ROUTE_SESSION_ID] = {}
        self.routes = routes
        self.count = 0

    def add(self, routes):
        for route in routes:
            self.count += 1
            trains_id = []
            for train in route['trains']:
                trains_id.append(str(train.id))
            self.routes[str(self.count)] = {
                'from_city': str(route['from_city'].id),
                'to_city': str(route['to_city'].id),
                'trains': trains_id,
                'total_time': route['total_time']
            }
        self.save()

    def get_route(self, route_id):
        route = copy.deepcopy(self.routes.get(str(route_id)))
        route['from_city'] = City.objects.get(pk=route['from_city'])
        route['to_city'] = City.objects.get(pk=route['to_city'])
        route['trains'] = Train.objects.filter(id__in=route['trains'])
        route['id'] = route_id
        return route

    def __iter__(self):
        """preserved helps save order in qs"""
        routes = copy.deepcopy(self.routes)
        for key, route in routes.items():
            trains_id = [i for i in route['trains']]
            from_city_id = route['from_city']
            to_city_id = route['to_city']
            preserved = Case(*[When(pk=pk, then=pos) for pos, pk in enumerate(trains_id)])
            trains = Train.objects.filter(id__in=trains_id).order_by(preserved)
            route['id'] = int(key)
            route['trains'] = [train for train in trains]
            route['from_city'] = City.objects.get(pk=from_city_id)
            route['to_city'] = City.objects.get(pk=to_city_id)
            yield route

    def __len__(self):
        return len(self.routes.values())

    def clear(self):
        del self.session[settings.ROUTE_SESSION_ID]
        self.session.modified = True
        # self.save()
        # print(self.session[settings.ROUTE_SESSION_ID])

    def save(self):
        """Сохранение корзины в сессии"""
        self.session[settings.ROUTE_SESSION_ID] = self.routes
        self.session.modified = True

apps/routes/tests.py
from django.core.exceptions import ValidationError
from django.test import TestCase
from django.urls import reverse
from apps.routes import views as route_views
from apps.routes import graph as gp
from apps.cities import views as cities_views
from apps.routes.forms import RouteForm
from apps.trains.models import Train
from apps.cities.models import City
from apps.routes.route import SessionRoute


class RoutesTestCase(TestCase):

    def setUp(self) -> None:
        self.city_A = City.objects.create(name='A')
        self.city_B = City.objects.create(name='B')
        self.city_C = City.objects.create(name='C')
        self.city_D = City.objects.create(name='D')
        self.city_E = City.objects.create(name='E')
        t1 = Train(name='t1', from_city=self.city_A, to_city=self.city_B, travel_time=9)
        t1.save()
        t2 = Train(name='t2', from_city=self.city_B, to_city=self.city_D, travel_time=8)
        t2.save()
        t3 = Train(name='t3', from_city=self.city_A, to_city=self.city_C, travel_time=7)
        t3.save()
        t4 = Train(name='t4', from_city=self.city_C, to_city=self.city_B, travel_time=6)
        t4.save()
        t5 = Train(name='t5', from_city=self.city_B, to_city=self.city_E, travel_time=3)
        t5.save()
        t6 = Train(name='t6', from_city=self.city_B, to_city=self.city_A, travel_time=11)
        t6.save()
        t7 = Train(name='t7', from_city=self.city_A, to_city=self.city_C, travel_time=10)
        t7.save()
        t8 = Train(name='t8', from_city=self.city_E, to_city=self.city_D, travel_time=5)
        t8.save()
        t9 = Train(name='t9', from_city=self.city_D, to_city=self.city_E, travel_time=4)
        t9.save()
        self.graph = gp.get_graph()

    def test_model_city_duplicate(self):
        try:
            a_city = City(name='A')
            a_city.full_clean()
        except ValidationError as e:
            self.assertEqual({'name': ['Город with this Город already exists.']}, e.message_dict)

    def test_model_train_duplicate_name(self):
        try:
            train_2 = Train(name='t2', from_city=self.city_B, to_city=self.city_D, travel_time=7)
            train_2.full_clean()
        except ValidationError as e:
            self.assertEqual({'name': ['Поезд with this Название already exists.']}, e.message_dict)

    def test_train_duplicate_by_cities_and_travel_time(self):
        try:
            train_2 = Train(name='t12', from_city=self.city_B, to_city=self.city_D, travel_time=7)
            train_2.full_clean()
        except ValidationError as e:
            self.assertEqual({'__all__': ['Измените время в пути']}, e.message_dict)

    def test_routes_home_view(self):
        response = self.client.get(reverse('routes:home'))
        self.assertEqual(200, response.status_code)
        self.assertTemplateUsed(response, template_name='routes/home.html')
        self.assertEqual(route_views.home, response.resolver_match.func)

    def test_cbv_city_detail(self):
        response = self.client.get(reverse('cities:detail', kwargs={'pk': self.city_A.id}))
        self.assertEqual(200, response.status_code)
        self.assertTemplateUsed(response, template_name='cities/detail.html')
        self.assertEqual(cities_views.CityDetailView.as_view().__name__, response.resolver_match.func.__name__)

    def test_find_all_routes(self):
        all_ways = list(gp.dfs_paths(self.graph, self.city_A.id, self.city_E.id))
        self.assertEqual(len(all_ways), 4)

    def test_form_is_valid(self):
        form_data = {'from_city': self.city_A.id, 'to_city': self.city_E.id,
                     'across_cities': [self.city_C.id], 'travel_time': 30}
        form = RouteForm(form_data)
        self.assertTrue(form.is_valid())

    def test_order_trains_in_route(self):
        self.client.get(reverse('routes:home'))
        request = self.client
        form_data = {'from_city': self.city_A.id, 'to_city': self.city_E.id,
                     'across_cities': [self.city_C.id, self.city_D.id], 'travel_time': 30}
        form = RouteForm(form_data)
        form.is_valid()
        data = form.cleaned_data
        trains = data['trains']
        SessionRoute(request).clear()
        routes = SessionRoute(request)
        routes.add(trains)
        lst = []
        for route in routes:
            lst.extend([i.from_city.name for i in route['trains']])
        self.assertEqual(lst, ['A', 'C', 'B', 'D'])

    def test_find_routes_messages_time_error(self):
        response = self.client.post('/find/', {'from_city': self.city_A.id, 'to_city': self.city_E.id,
                                               'across_cities': [self.city_C.id], 'travel_time': 10})
        self.assertContains(response, 'Время в пути больше заданного', 1, 200)

    def test_find_routes_messages_across_cities_error(self):
        response = self.client.post('/find/', {'from_city': self.city_B.id, 'to_city': self.city_E.id,
                                               'across_cities': [self.city_C.id], 'travel_time': 20})
        self.assertContains(response, 'Маршрут через эти города невозможен', 1, 200)

apps/routes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, DeleteView
from .forms import RouteForm, RouteCreateForm, DivErrorList
from .models import Route
from .route import SessionRoute


def home(request):
    form = RouteForm()
    return render(request, 'routes/home.html', {'form': form})


def find_routes(request):
    if request.method == "POST":
        form = RouteForm(request.POST or None, error_class=DivErrorList)
        if form.is_valid():
            data = form.cleaned_data
            from_city = data['from_city']
            to_city = data['to_city']
            trains = data['trains']
            SessionRoute(request).clear()
            routes = SessionRoute(request)
            routes.add(trains)

            cities = {'from_city': from_city.name, 'to_city': to_city.name}
            context = {'form': RouteForm(error_class=DivErrorList), 'routes': routes, 'cities': cities}
            return render(request, 'routes/home.html', context)
        return render(request, 'routes/home.html', {'form': form})
    else:
        messages.error(request, 'Создайте маршрут')
        form = RouteForm()
        return render(request, 'routes/home.html', {'form': form})


def save_route(request, route_id):
    if request.method == 'POST':
        form = RouteCreateForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            name = form_data['name']
            route = SessionRoute(request)
            data = route.get_route(route_id)
            route = Route(
                name=name,
                from_city=data['from_city'],
                to_city=data['to_city'],
                travel_time=data['total_time'])
            route.save()
            for train in data['trains']:
                route.across_cities.add(train.id)
            messages.error(request, 'Маршрут сохранен')
            return HttpResponseRedirect('/')
    else:
        route = SessionRoute(request)
        data = route.get_route(route_id)
        if data:
            form = RouteCreateForm()
            context = {'form': form, 'route': data}
            return render(request, 'routes/create.html', context)
        else:
            messages.error(request, 'Невозможно сохранить несуществующий маршрут')
            return HttpResponseRedirect('/')


class RouteDetailView(DetailView):
    queryset = Route.objects.all()
    context_object_name = 'route'
    template_name = 'routes/detail.html'


class RouteListView(ListView):
    queryset = Route.objects.all()
    context_object_name = 'route_list'
    template_name = 'routes/list.html'


class RouteDeleteView(LoginRequiredMixin, DeleteView):
    model = Route
    login_url = '/login/'
    template_name = 'routes/delete.html'
    success_url = reverse_lazy('routes:home')

templates/routes/create.html
{% extends 'base.html' %}
{% block title %}Сохранить маршрут{% endblock %}
{% block content %}
    <div class="container my-4">
        <h1 class="display-4">Сохранить маршрут</h1>
        <div class="row mx-auto my-4">
            <div class="col-md-8">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>Маршрут из г. {{ route.from_city }} в г. {{ route.to_city }} продолжительностью {{ route.total_time }} ч.</p>
                    <p>Маршрут состоит из:</p>
                    {% for train in route.trains %}
                        <p>Поезд № {{ train.name }} следующий из г. {{ train.from_city }} в г. {{ train.to_city }}.
                        Время в пути {{ train.travel_time }} ч.</p>
                    {% endfor %}

                    <input class="btn btn-light" type="submit" role="button" value="Сохранить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/routes/delete.html
{% extends 'base.html' %}
{% block title %}Удалить маршрут?{% endblock %}
{% block content %}
    <div class="container my-4">
        <h3 class="">Удалить маршрут</h3>
        <div class="row mx-auto my-4">
            <div class="col-md-6 my-4">
                <form action="" method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить маршрут "{{ object.name }}"?</p>
                    <input class="btn btn-light" type="submit" role="button" value="Удалить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/routes/detail.html
{% extends 'base.html' %}
{% block title %}Маршруты{% endblock title %}
{% block content %}
    <div class="container my-4">
        <h1 class="text-center my-4">Список маршрутов</h1>
        <div class="row">
            <div class="col-md-12 mx-auto">
                <table class="table">
                    <thead class="thead-dark rounded">
                    <tr>
                        <th scope="col">Название маршрута</th>
                        <th scope="col">Откуда</th>
                        <th scope="col">Куда</th>
                        <th scope="col">Время в пути</th>
                        <th scope="col">Список поездов по маршруру</th>
                        <th scope="col">&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">{{ route.name }}</th>
                            <th>{{ route.from_city }}</th>
                            <th>{{ route.to_city }}</th>
                            <th>{{ route.travel_time }} ч.</th>
                            <th> {% for train in route.across_cities.all %}Поезд № {{ train.name }} из г. {{ train.from_city }} в г. {{ train.to_city }}
                                <br>{% endfor %}</th>
                            <th><a class="btn btn-danger btn-sm" href="{% url 'routes:delete' pk=route.pk %}"
                                   role="button">Удалить</a></th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/routes/home.html
{% extends 'base.html' %}
{% block title %}Поиск маршрута{% endblock title %}
{% block content %}
    <div class="container my-4">
        <h1 class="display-4 text-center">Поиск маршрута</h1>
        {% if routes %}
            <div class="row mx-auto my-4">
                <div class="col-md-8 mx-auto">
                    <h3 class="text-center">
                        {% if routes|length == 1 %}Маршрут{% else %}Маршруты{% endif %}
                         из г. {{ cities.from_city }} в г. {{ cities.to_city }}</h3>
                {% for route in routes %}
                    {% if forloop.first %}
                        <h5 class="text-center my-4">Самый короткий маршрут: {{ route.total_time }} ч.</h5>
                    {% endif %}
                    <table class="table my-4">
                        <thead class="thead-dark rounded">
                            <tr>
                                <th scope="col">Список поездов</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for train in route.trains %}
                            <tr>
                                <th>Поезд № <strong>{{ train.name }}</strong>, следующий из г. {{ train.from_city.name }} в г. {{ train.to_city.name }}.
                                    Время в пути {{ train.travel_time }} ч.</th>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p><strong>Время в пути {{ route.total_time }} ч.</strong></p>
                        <a role="button" class="btn btn-success btn-sm" href="{% url 'routes:save_route' route_id=route.id %}">Сохранить маршрут</a>
                {% endfor %}
                </div>
            </div>
        {% endif %}
        <div class="row mx-auto my-4">
            <div class="col-md-6 mx-auto">
                <form action="{% url 'routes:find' %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-light" type="submit" role="button" value="Найти">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/routes/list.html
{% extends 'base.html' %}
{% block title %}Список маршрутов{% endblock title %}
{% block content %}
    <div class="container my-4">
        <h1 class="text-center my-4">Список маршрутов</h1>
        <div class="row">
            <div class="col-md-10 mx-auto">
                <table class="table">
                    <thead class="thead-dark rounded">
                    <tr>
                        <th scope="col">Название маршрута</th>
                        <th scope="col">Откуда</th>
                        <th scope="col">Куда</th>
                        <th scope="col">Время в пути</th>


                    </tr>
                    </thead>
                    <tbody>
                    {% for route in route_list %}
                        <tr>
                            <th scope="row"><a href="{% url 'routes:detail' pk=route.pk %}">{{ route.name }}</a></th>
                            <th>{{ route.from_city }}</th>
                            <th>{{ route.to_city }}</th>
                            <th>{{ route.travel_time }} ч.</th>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}